# Generated by Django 3.0.5 on 2020-04-25 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(max_length=40)),
                ('b5_consc', models.FloatField()),
                ('b5_extr', models.FloatField()),
                ('b5_open', models.FloatField()),
                ('b5_agree', models.FloatField()),
                ('b5_neur', models.FloatField()),
                ('is_startuper', models.BooleanField(default=False)),
                ('twitter_username', models.CharField(max_length=100)),
                ('instagram_username', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
