# Generated by Django 3.0.5 on 2020-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohack', '0003_auto_20200426_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercharacteristics',
            name='activity_score',
        ),
        migrations.AddField(
            model_name='usercharacteristics',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usercharacteristics',
            name='b5_agree',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='usercharacteristics',
            name='b5_consc',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='usercharacteristics',
            name='b5_extr',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='usercharacteristics',
            name='b5_neur',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='usercharacteristics',
            name='b5_open',
            field=models.FloatField(default=0.5),
        ),
    ]
