# Generated by Django 3.0.5 on 2020-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohack', '0005_auto_20200426_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharacteristics',
            name='interest',
            field=models.TextField(default='investions'),
        ),
    ]
